### example of the configuration in home assistant

mqtt:
  sensor:
    - name: "室外温度"
      object_id: "temp_outdoor"
      state_topic: "homeassistant/weatherstation/temperature_out"
      device_class: "temperature"
      unit_of_measurement: "°C"
    - name: "室外湿度"
      object_id: "humidity_outdoor"
      state_topic: "homeassistant/weatherstation/humidity_out"
      device_class: "humidity"
      unit_of_measurement: "%"
    - name: "露点"
      object_id: "dew_point"
      state_topic: "homeassistant/weatherstation/dewpoint"
      device_class: "temperature"
      unit_of_measurement: "°C"
    - name: "风向"
      object_id: "wind_direction_degree"
      state_topic: "homeassistant/weatherstation/wind_direction"
      unit_of_measurement: "°"
      icon: "hass:windsock"
    - name: "Medium Wind"
      object_id: "风速"
      state_topic: "homeassistant/weatherstation/wind_speed"
      unit_of_measurement: "km/h"
      icon: "hass:weather-windy"
    - name: "阵风风速"
      object_id: "wind_gustspeed"
      state_topic: "homeassistant/weatherstation/wind_gust_speed"
      unit_of_measurement: "km/h"
      icon: "hass:weather-windy"
    - name: "雨量"
      object_id: "rain_rate"
      state_topic: "homeassistant/weatherstation/rain_rate"
      unit_of_measurement: "mm/h"
      icon: "hass:weather-pouring"
    - name: "太阳辐射能量"
      object_id: "solar_radiation"
      state_topic: "homeassistant/weatherstation/solar_radiation"
      unit_of_measurement: "w/m2"
      icon: "hass:solar-power-variant"
    - name: "紫外线指数"
      object_id: "uv_index"
      state_topic: "homeassistant/weatherstation/uv_index"
      icon: "hass:sun-wireless"
    - name: "气象站电量"
      object_id: "pws_battery"
      state_topic: "homeassistant/weatherstation/low_battery"
      device_class: "battery"
      unit_of_measurement: "%"
      icon: "hass:battery"
