### example of the configuration in home assistant

mqtt:
  sensor:
    - name: "Outdoor Temperature"
      object_id: "temp_outdoor"
      state_topic: "homeassistant/weatherstation/temperature_out"
      device_class: "temperature"
      unit_of_measurement: "°C"
    - name: "Outdoor Humidity"
      object_id: "humidity_outdoor"
      state_topic: "homeassistant/weatherstation/humidity_out"
      device_class: "humidity"
      unit_of_measurement: "%"
    - name: "Dew Point"
      object_id: "dew_point"
      state_topic: "homeassistant/weatherstation/dewpoint"
      device_class: "temperature"
      unit_of_measurement: "°C"
    - name: "Wind Direction"
      object_id: "wind_direction_degree"
      state_topic: "homeassistant/weatherstation/wind_direction"
      unit_of_measurement: "°"
      icon: "hass:windsock"
    - name: "Medium Wind"
      object_id: "wind_speed"
      state_topic: "homeassistant/weatherstation/wind_speed"
      unit_of_measurement: "km/h"
      icon: "hass:weather-windy"
    - name: "Wind Gust"
      object_id: "wind_gustspeed"
      state_topic: "homeassistant/weatherstation/wind_gust_speed"
      unit_of_measurement: "km/h"
      icon: "hass:weather-windy"
    - name: "Solar Radiation"
      object_id: "solar_radiation"
      state_topic: "homeassistant/weatherstation/solar_radiation"
      unit_of_measurement: "w/m2"
      icon: "hass:solar-power-variant"
    - name: "UV index"
      object_id: "uv_index"
      state_topic: "homeassistant/weatherstation/uv_index"
      icon: "hass:sun-wireless"
    - name: "Rain Rate"
      object_id: "rain_rate"
      state_topic: "homeassistant/weatherstation/rain_rate"
      unit_of_measurement: "mm/h"
      icon: "hass:weather-pouring"
    - name: "Battery Weather Station"
      object_id: "pws_battery"
      state_topic: "homeassistant/weatherstation/low_battery"
      device_class: "battery"
      unit_of_measurement: "%"
      icon: "hass:battery"
