name: "Weather Station to MQTT"
description: "Intercepts data from Weather Station directed to Weather Underground and publish it through MQTT"
version: "0.2.0"
slug: "weather_station_mqtt"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
services:
  - "mqtt:need"
ports:
  8087/tcp: 8087
ports_description:
  8087/tcp: HTTP listening port
options:
  mqtt_broker_host: "hass_ip"
  mqtt_broker_port:  1883
  mqtt_username: "mqttuser"
  mqtt_password: "mqttpassword"
schema:
  mqtt_broker_host: str
  mqtt_broker_port: int
  mqtt_username: str
  mqtt_password: password
